"""
Analyze Catalytic Activity (Decoupled Plotting).

Reads generic standardized Binding Energies exported by `genbindingenergy` 
and evaluates fully targeted Reaction Mechanisms (OER, ORR, CO2RR, etc).

Author: Hoje Chun
Contact: GitHub @hojechun
"""

import os
import sys
import argparse
import json
import traceback
from pathlib import Path
from typing import Any, Dict

# Add project root to python path to access src package
repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../.."))
if repo_root not in sys.path:
    sys.path.append(repo_root)

from src.utils.htvs.catalysis_utils import REACTIONS, load_external_corrections

def run_catalysis_analysis(args: argparse.Namespace) -> Dict[str, Any]:
    # Load external corrections from resource directory if available
    resource_path = os.path.join(os.path.dirname(__file__), "../resources/thermo_corrections.json")
    load_external_corrections(resource_path)

    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
        
    mechanism = REACTIONS[args.reaction]()
    
    try:
         with open(args.data_file, "r") as f:
             json_payload = json.load(f)
    except FileNotFoundError:
         raise FileNotFoundError(f"Could not locate binding energy file: {args.data_file}")
            
    # Calculate mechanism performance
    results = {}
    processed_labels = []
    
    for cl_id, sdata in json_payload.items():
        energies = sdata.get("energies", {})
        
        # Check completion of intermediate set
        if all(interm in energies for interm in mechanism.required_intermediates):
             name = sdata.get("label", f"Surface_{cl_id}")
             res = mechanism.calculate_steps(energies)
             results[name] = res
             processed_labels.append(name)
             print(f"[{name}] overpotential η = {res['eta']:.3f} V (PDS: Step {res['pds']})", file=sys.stderr)
    
    if not results:
        return {
            "status": "warning",
            "message": "No surfaces found with complete binding datasets."
        }
        
    out_json = out_dir / f"{args.reaction.lower()}_results.json"
    with open(out_json, "w") as f:
        json.dump(results, f, indent=2)
        
    mechanism.plot_free_energy(results, str(out_dir / f"{args.reaction.lower()}_free_energy_steps.png"))
    mechanism.plot_volcano(results, str(out_dir / f"{args.reaction.lower()}_volcano.png"))
    
    return {
        "status": "success",
        "processed_surfaces": processed_labels,
        "output_dir": str(args.output_dir),
        "results_json": str(out_json)
    }

def main():
    parser = argparse.ArgumentParser(description="Evaluate Generalized Catalytic Activity")
    parser.add_argument("--reaction", type=str, default="OER", choices=list(REACTIONS.keys()), help="Target catalytic reaction mechanism.")
    parser.add_argument("--data_file", type=str, required=True, help="Input JSON path encapsulating generic binding energies generated by 'genbindingenergy'.")
    parser.add_argument("--output_dir", type=str, default=".", help="Output directory for plots")
    args = parser.parse_args()
    
    try:
        results = run_catalysis_analysis(args)
        print(json.dumps(results, indent=2))
    except Exception as e:
        error_results = {
            "status": "error",
            "error": str(e),
            "traceback": traceback.format_exc()
        }
        print(json.dumps(error_results, indent=2))
        sys.exit(1)

if __name__ == "__main__":
    main()
